// ===== QUESTION DATA (Grade 6-8 International School) =====
const questions = {
  vocabulary: [
    // --- School/Academic ---
    {q:"The teacher gave us a new ___ to complete by Friday.", choices:["absence","assignment","substitute","permission"], answer:1, expl:"An assignment is a task or piece of work given to students by a teacher."},
    {q:"What does \"deadline\" mean?", choices:["The start of a project","The last day to submit work","A type of exam","A study break"], answer:1, expl:"A deadline is the latest time by which something must be completed or submitted."},
    {q:"A \"presentation\" is when you ___.", choices:["take a written test","speak in front of a group about a topic","read silently at your desk","do homework at home"], answer:1, expl:"A presentation means standing up and explaining a topic to an audience."},
    {q:"In science class, an \"experiment\" is ___.", choices:["a guess about what will happen","a test done to discover something","a chapter in the textbook","the final grade on a report"], answer:1, expl:"An experiment is a scientific test carried out to discover or prove something."},
    {q:"A \"hypothesis\" is ___.", choices:["the result of an experiment","a type of lab equipment","an educated guess you can test","a summary of your notes"], answer:2, expl:"A hypothesis is a prediction you make before an experiment that can be tested."},
    {q:"Your school \"schedule\" shows ___.", choices:["your test scores","which classes you have and when","the lunch menu","your homework answers"], answer:1, expl:"A schedule is a timetable that shows the plan of classes and their times."},
    {q:"You need \"permission\" from a teacher to ___.", choices:["sit in your assigned seat","open your textbook","leave the classroom early","listen during a lecture"], answer:2, expl:"Permission means approval or consent from someone in authority to do something."},
    {q:"If a student has an \"absence,\" it means ___.", choices:["they arrived early","they were not at school","they got a perfect score","they finished their work quickly"], answer:1, expl:"Absence means not being present; the student was not at school that day."},
    {q:"A \"substitute\" teacher is someone who ___.", choices:["teaches your class when your regular teacher is away","helps you after school","grades your exams","designs the curriculum"], answer:0, expl:"A substitute replaces someone temporarily \u2014 here, a teacher filling in for the regular one."},
    {q:"The \"curriculum\" is ___.", choices:["a single homework assignment","the school cafeteria menu","the set of subjects and topics taught at a school","a type of classroom"], answer:2, expl:"Curriculum refers to the overall plan of subjects and content taught at a school."},
    // --- Emotions ---
    {q:"She felt ___ before her presentation because she hadn't practiced enough.", choices:["confident","anxious","relieved","grateful"], answer:1, expl:"Anxious means feeling worried or nervous about something uncertain."},
    {q:"After struggling with the math problem for an hour, Tom felt ___.", choices:["motivated","embarrassed","frustrated","jealous"], answer:2, expl:"Frustrated means feeling upset or annoyed because you cannot achieve something."},
    {q:"When she finally passed her exam, she felt ___ and proud.", choices:["overwhelmed","exhausted","anxious","confident"], answer:3, expl:"Confident means feeling sure about your own abilities and success."},
    {q:"He was ___ when his test came back with a much higher score than expected.", choices:["frustrated","jealous","embarrassed","relieved"], answer:3, expl:"Relieved means feeling happy because something stressful is over or went well."},
    {q:"Having three projects due on the same day made her feel ___.", choices:["grateful","motivated","overwhelmed","jealous"], answer:2, expl:"Overwhelmed means feeling like there is too much to handle at once."},
    {q:"He tripped in front of the whole class and felt very ___.", choices:["confident","motivated","exhausted","embarrassed"], answer:3, expl:"Embarrassed means feeling ashamed or awkward in front of others."},
    {q:"The coach's speech before the game made the whole team feel ___.", choices:["anxious","motivated","frustrated","jealous"], answer:1, expl:"Motivated means feeling eager and driven to do something."},
    {q:"She was ___ of her classmate who won the art competition.", choices:["relieved","grateful","exhausted","jealous"], answer:3, expl:"Jealous means wanting what someone else has, or feeling envious of their success."},
    {q:"I'm ___ to my tutor for helping me improve my writing.", choices:["frustrated","embarrassed","grateful","anxious"], answer:2, expl:"Grateful means feeling thankful and appreciative for someone's help."},
    // --- Mixed completion ---
    {q:"After running the 5K race, all the students felt completely ___.", choices:["motivated","jealous","anxious","exhausted"], answer:3, expl:"Exhausted means extremely tired, with no energy left."},
    {q:"The teacher asked for a volunteer, but nobody had the ___ to raise their hand.", choices:["absence","permission","confidence","schedule"], answer:2, expl:"Confidence is the belief in your own ability; without it, you hesitate to act."},
    {q:"Our group needs to ___ our findings to the whole class tomorrow.", choices:["postpone","present","substitute","assign"], answer:1, expl:"Present means to show or explain something to an audience."},
    {q:"The school changed its ___ to include a new coding class.", choices:["deadline","hypothesis","absence","curriculum"], answer:3, expl:"Curriculum is the set of courses and content taught at a school; adding coding changes it."},
    {q:"Please ask for ___ before using the lab equipment.", choices:["experiment","permission","schedule","presentation"], answer:1, expl:"Permission means getting approval before doing something, especially from authority."},
    {q:"His ___ from school for a week meant he had a lot of work to catch up on.", choices:["deadline","substitute","absence","curriculum"], answer:2, expl:"Absence means being away; missing a week of school means lots of missed work."},
    // --- Academic words ---
    {q:"The teacher asked us to ___ the data from the experiment.", choices:["ignore","analyze","memorize","decorate"], answer:1, expl:"Analyze means to examine something in detail to understand it or draw conclusions."},
    {q:"Scientists must ___ their findings with evidence.", choices:["guess","support","hide","forget"], answer:1, expl:"Support means to back up or prove something with facts and evidence."},
    {q:"To ___ means to reach a decision after thinking carefully.", choices:["conclude","begin","confuse","postpone"], answer:0, expl:"Conclude means to arrive at a judgment or decision after reasoning."},
    {q:"What does \"evaluate\" mean?", choices:["To copy someone's work","To judge the quality or value of something","To throw something away","To repeat a lesson"], answer:1, expl:"Evaluate means to assess or judge how good, useful, or important something is."},
    {q:"The ___ from the survey showed that most students prefer group work.", choices:["evidence","absence","substitute","deadline"], answer:0, expl:"Evidence is information or data that supports a conclusion or belief."},
    // --- Social/emotional words ---
    {q:"___ is the ability to understand how someone else feels.", choices:["Jealousy","Empathy","Conflict","Economy"], answer:1, expl:"Empathy means being able to share and understand another person's feelings."},
    {q:"When two people disagree strongly, they are having a ___.", choices:["cooperation","perspective","conflict","migration"], answer:2, expl:"A conflict is a serious disagreement or argument between people."},
    {q:"Seeing a problem from another person's ___ can help you understand them.", choices:["schedule","perspective","absence","curriculum"], answer:1, expl:"Perspective means a particular way of thinking about or viewing something."},
    {q:"To ___ means to work together with others toward a common goal.", choices:["compete","cooperate","evaluate","migrate"], answer:1, expl:"Cooperate means to work jointly with others to achieve a shared purpose."},
    {q:"When two sides ___, they discuss and try to reach an agreement.", choices:["negotiate","ignore","abandon","memorize"], answer:0, expl:"Negotiate means to discuss something in order to reach a compromise or agreement."},
    // --- Science words ---
    {q:"Any living thing, such as a plant or animal, is called an ___.", choices:["object","organism","opinion","obstacle"], answer:1, expl:"An organism is any individual living thing \u2014 plants, animals, bacteria, etc."},
    {q:"An ___ is a community of living things and their environment.", choices:["equation","ecosystem","election","escalator"], answer:1, expl:"An ecosystem includes all living organisms and the physical environment they interact with."},
    {q:"___ is the force that pulls objects toward the center of the Earth.", choices:["Gravity","Friction","Pressure","Velocity"], answer:0, expl:"Gravity is the natural force that attracts objects toward the Earth."},
    {q:"A ___ is the smallest unit of a chemical compound.", choices:["mineral","molecule","muscle","monument"], answer:1, expl:"A molecule is a group of atoms bonded together, forming the smallest unit of a compound."},
    {q:"When a species changes over a long time to better survive, it is said to ___.", choices:["dissolve","revolve","evolve","resolve"], answer:2, expl:"Evolve means to develop gradually over many generations through natural selection."},
    {q:"The ___ of the heart is to pump blood throughout the body.", choices:["function","fiction","fraction","friction"], answer:0, expl:"Function means the purpose or role that something has."},
    // --- History/social studies words ---
    {q:"A ___ is a complex society with its own culture, government, and laws.", choices:["civilization","vacation","celebration","imagination"], answer:0, expl:"A civilization is an advanced human society with organized government, culture, and technology."},
    {q:"___ is a system of government where people vote for their leaders.", choices:["Monarchy","Democracy","Dictatorship","Aristocracy"], answer:1, expl:"Democracy means government by the people, usually through elected representatives."},
    {q:"A ___ is a sudden and dramatic change in government or society.", choices:["revolution","reservation","recreation","repetition"], answer:0, expl:"A revolution is a forceful overthrow of a government or social system."},
    {q:"___ means the movement of people from one place to another.", choices:["Migration","Meditation","Motivation","Multiplication"], answer:0, expl:"Migration is the large-scale movement of people from one region or country to another."},
    {q:"The ___ of a country refers to its system of producing and using money and goods.", choices:["ecology","economy","emergency","embassy"], answer:1, expl:"Economy is the system of trade, industry, and money management in a region or country."},
    // --- More academic vocabulary ---
    {q:"The students were asked to ___ the two poems and find similarities.", choices:["compare","compete","complain","compose"], answer:0, expl:"Compare means to examine two or more things to identify similarities and differences."},
    {q:"A ___ is a short summary of the main points of a text.", choices:["chapter","summary","glossary","bibliography"], answer:1, expl:"A summary is a brief statement of the main points of something."},
    {q:"The word \"significant\" most closely means ___.", choices:["unimportant","large in amount or effect","confusing","temporary"], answer:1, expl:"Significant means important, notable, or having a great effect."},
    {q:"To ___ information means to put it into groups based on shared features.", choices:["classify","memorize","translate","illustrate"], answer:0, expl:"Classify means to arrange or organize things into categories based on shared characteristics."},
    {q:"A ___ is a belief or idea that has not yet been proven.", choices:["fact","theory","result","summary"], answer:1, expl:"A theory is an explanation based on evidence and reasoning, but not yet fully proven."},
    {q:"The opposite of \"ancient\" is ___.", choices:["modern","broken","foreign","natural"], answer:0, expl:"Ancient means very old; modern means current or recent \u2014 they are opposites."},
    {q:"To ___ means to make something clear and easy to understand.", choices:["complicate","clarify","criticize","celebrate"], answer:1, expl:"Clarify means to explain something more clearly so it can be understood."},
    {q:"The ___ of the story is the lesson it teaches.", choices:["moral","title","setting","character"], answer:0, expl:"The moral is the ethical lesson or message that a story conveys."},
    {q:"Something that is ___ happens every year.", choices:["annual","daily","weekly","monthly"], answer:0, expl:"Annual means occurring once every year."},
    {q:"If something is ___, it can last for a long time without causing harm.", choices:["temporary","sustainable","fragile","artificial"], answer:1, expl:"Sustainable means able to continue over time without depleting resources or causing damage."},
    {q:"To ___ means to give out or share resources among a group.", choices:["distribute","disturb","dissolve","distinguish"], answer:0, expl:"Distribute means to hand out or divide something among several people."},
    {q:"A ___ is an official document that proves you completed a course.", choices:["certificate","ceremony","circumstance","calendar"], answer:0, expl:"A certificate is a document showing achievement or completion of a program."},
    {q:"The teacher asked us to ___ the main idea of the paragraph.", choices:["identify","ignore","illustrate","imitate"], answer:0, expl:"Identify means to recognize or point out what something is."},
    {q:"Something ___ is expected to happen and cannot be avoided.", choices:["invisible","inevitable","innocent","informal"], answer:1, expl:"Inevitable means certain to happen; unavoidable."}
  ],
  grammar: [
    // --- Present perfect ---
    {q:"I ___ already finished my homework.", choices:["had","have","am","was"], answer:1, expl:"'I have finished' is present perfect. Use 'have' with I/you/we/they."},
    {q:"She ___ never visited another country before.", choices:["have","is","has","was"], answer:2, expl:"'She' is third person singular, so we use 'has' in present perfect (has + past participle)."},
    {q:"We ___ studied three chapters so far this semester.", choices:["are","have","had","will"], answer:1, expl:"'So far' signals present perfect tense. 'We have studied' shows an action continuing to now."},
    // --- Past perfect ---
    {q:"She ___ left the classroom before the bell rang.", choices:["has","have","had","is"], answer:2, expl:"Past perfect uses 'had' + past participle to show one past event happened before another."},
    {q:"By the time we arrived, the movie ___.", choices:["has started","had already started","is starting","will start"], answer:1, expl:"'By the time we arrived' refers to a past moment; the movie started even earlier, so use past perfect."},
    {q:"They ___ finished the experiment before the teacher collected the reports.", choices:["have","has","had","are"], answer:2, expl:"Two past events: finishing came first, so use past perfect 'had finished'."},
    // --- Passive voice ---
    {q:"The experiment ___ by the science class last week.", choices:["conducted","was conducted","has conducted","is conducting"], answer:1, expl:"Passive voice: the subject receives the action. 'Was conducted' = past passive."},
    {q:"The school rules ___ in the student handbook.", choices:["are explained","have explaining","is explain","were explaining"], answer:0, expl:"Passive voice with plural subject 'rules' uses 'are explained' (are + past participle)."},
    {q:"A new library ___ on campus next year.", choices:["builds","is building","will be built","has built"], answer:2, expl:"Future passive: 'will be built' because the library receives the action of being built."},
    // --- Conditional ---
    {q:"If I study hard, I ___ pass the test.", choices:["would","will","had","am"], answer:1, expl:"First conditional (real/possible): If + present simple, will + base verb."},
    {q:"If she ___ more time, she would join the debate club.", choices:["has","have","had","will have"], answer:2, expl:"Second conditional (unreal/hypothetical): If + past simple ('had'), would + base verb."},
    {q:"We will miss the bus if we ___ hurry.", choices:["won't","hadn't","don't","aren't"], answer:2, expl:"First conditional: If + present simple. 'Don't hurry' is the present simple negative."},
    // --- Relative clauses ---
    {q:"The teacher ___ helped me is very kind.", choices:["which","whose","whom","who"], answer:3, expl:"'Who' is used for people as the subject of a relative clause."},
    {q:"The book ___ I borrowed from the library was fascinating.", choices:["who","whose","that","whom"], answer:2, expl:"'That' (or 'which') is used for things. 'Who' is only for people."},
    {q:"The student ___ project won first place gave a speech.", choices:["who","whose","which","that"], answer:1, expl:"'Whose' shows possession \u2014 the project belongs to the student."},
    // --- Reported speech ---
    {q:"He said that he ___ tired after the long practice.", choices:["is","was","will be","has been"], answer:1, expl:"In reported speech, present tense 'is' shifts back to past tense 'was'."},
    {q:"She told me she ___ submit her essay the next day.", choices:["will","is going to","would","can"], answer:2, expl:"In reported speech, 'will' shifts to 'would'. 'The next day' replaces 'tomorrow'."},
    {q:"The teacher announced that the test ___ postponed.", choices:["is","will","has","had been"], answer:3, expl:"In reported speech, present perfect 'has been' shifts to past perfect 'had been'."},
    // --- Modal verbs ---
    {q:"You ___ submit your essay by Friday. It's required.", choices:["might","could","must","would"], answer:2, expl:"'Must' expresses obligation or requirement. It's required = you must do it."},
    {q:"She ___ be at the library; I saw her heading that way.", choices:["must","might","should","would"], answer:1, expl:"'Might' expresses possibility when you're not certain."},
    {q:"You ___ ask before borrowing someone else's notes.", choices:["would","might","could","should"], answer:3, expl:"'Should' gives advice or suggests the right thing to do."},
    // --- Articles ---
    {q:"We need to write ___ essay about climate change.", choices:["a","an","the","no article"], answer:1, expl:"'Essay' starts with a vowel sound, so we use 'an' (not 'a')."},
    {q:"___ students in our class passed the final exam.", choices:["A","An","The","No article"], answer:2, expl:"'The students' refers to a specific group \u2014 the ones in our class."},
    {q:"She wants to become ___ engineer when she grows up.", choices:["a","an","the","no article"], answer:1, expl:"'Engineer' starts with a vowel sound, so we use 'an'."},
    {q:"___ homework that was assigned yesterday is due tomorrow.", choices:["A","An","The","No article"], answer:2, expl:"'The' is used because we're talking about specific homework (assigned yesterday)."},
    // --- More passive voice ---
    {q:"The results ___ to the class by the teacher tomorrow.", choices:["will present","will be presented","are presenting","have presented"], answer:1, expl:"Future passive: 'will be presented' because the results receive the action."},
    {q:"English ___ in many countries around the world.", choices:["speaks","is spoken","has speaking","were speak"], answer:1, expl:"Present passive: English receives the action of being spoken."},
    {q:"The homework ___ before the students left.", choices:["was collected","has collecting","is collected","were collect"], answer:0, expl:"Past passive: 'was collected' \u2014 the homework received the action of being collected."},
    // --- Present perfect vs past simple ---
    {q:"I ___ to London three times. (experience up to now)", choices:["went","have been","was going","had gone"], answer:1, expl:"Present perfect 'have been' for life experiences up to now."},
    {q:"She ___ her project last night. (specific past time)", choices:["has finished","have finished","finished","finishes"], answer:2, expl:"Past simple 'finished' with 'last night' \u2014 a specific time in the past."},
    {q:"They ___ here since 2020. (continuing to now)", choices:["lived","have lived","are living","were living"], answer:1, expl:"Present perfect 'have lived' with 'since' \u2014 started in the past and continues."},
    {q:"___ you ever ___ sushi?", choices:["Did / eat","Have / eaten","Are / eating","Were / eaten"], answer:1, expl:"Present perfect for life experiences: 'Have you ever eaten...?'"},
    // --- More reported speech ---
    {q:"She asked me where I ___.", choices:["live","lived","am living","have lived"], answer:1, expl:"In reported questions, the tense shifts back: 'live' becomes 'lived'."},
    {q:"He told us that he ___ the answer.", choices:["doesn't know","didn't know","don't know","hasn't know"], answer:1, expl:"In reported speech, 'doesn't know' shifts to 'didn't know'."},
    {q:"The principal said that school ___ start earlier next month.", choices:["will","would","can","shall"], answer:1, expl:"In reported speech, 'will' changes to 'would'."},
    // --- More relative clauses ---
    {q:"The city ___ we visited last summer was beautiful.", choices:["who","which","whose","whom"], answer:1, expl:"'Which' or 'that' is used for places and things in relative clauses."},
    {q:"The girl ___ bag was stolen reported it to the police.", choices:["who","which","whose","that"], answer:2, expl:"'Whose' shows possession \u2014 the bag belongs to the girl."},
    {q:"Is this the reason ___ you were late?", choices:["which","why","whose","whom"], answer:1, expl:"'Why' is used in relative clauses referring to a reason."},
    // --- Gerunds vs infinitives ---
    {q:"I enjoy ___ English every day.", choices:["study","to study","studying","studied"], answer:2, expl:"'Enjoy' is always followed by a gerund (-ing form): 'enjoy studying'."},
    {q:"She wants ___ a doctor when she grows up.", choices:["become","becoming","to become","became"], answer:2, expl:"'Want' is followed by an infinitive (to + base verb): 'want to become'."},
    {q:"They finished ___ the project before midnight.", choices:["to do","doing","do","did"], answer:1, expl:"'Finish' is followed by a gerund: 'finished doing'."},
    {q:"He decided ___ harder for the next exam.", choices:["studying","to study","study","studied"], answer:1, expl:"'Decide' is followed by an infinitive: 'decided to study'."},
    {q:"We avoid ___ our phones during class.", choices:["to use","using","use","used"], answer:1, expl:"'Avoid' is followed by a gerund: 'avoid using'."},
    {q:"The teacher suggested ___ the chapter again.", choices:["to read","read","reading","reads"], answer:2, expl:"'Suggest' is followed by a gerund: 'suggested reading'."},
    {q:"I hope ___ a good grade on the test.", choices:["getting","to get","get","got"], answer:1, expl:"'Hope' is followed by an infinitive: 'hope to get'."},
    {q:"She keeps ___ the same mistake in her essays.", choices:["to make","make","making","made"], answer:2, expl:"'Keep' is followed by a gerund: 'keeps making'."},
    // --- Prepositions ---
    {q:"The report focuses ___ the effects of pollution.", choices:["in","at","on","by"], answer:2, expl:"'Focus on' is the correct preposition combination."},
    {q:"We are responsible ___ completing our homework.", choices:["of","for","to","with"], answer:1, expl:"'Responsible for' is the correct preposition."},
    {q:"The experiment resulted ___ an unexpected discovery.", choices:["to","for","in","on"], answer:2, expl:"'Result in' means to cause or lead to a particular outcome."},
    {q:"She is interested ___ studying marine biology.", choices:["on","for","at","in"], answer:3, expl:"'Interested in' is the correct preposition combination."},
    {q:"The solution depends ___ many different factors.", choices:["in","on","for","to"], answer:1, expl:"'Depend on' is the correct preposition."},
    {q:"He apologized ___ being late to class.", choices:["about","for","to","of"], answer:1, expl:"'Apologize for' is the correct preposition."},
    {q:"The essay consists ___ five paragraphs.", choices:["in","from","of","with"], answer:2, expl:"'Consist of' means to be made up of."},
    // --- Comparatives ---
    {q:"This test was ___ than the last one.", choices:["more difficult","most difficult","difficulter","the most difficult"], answer:0, expl:"Comparative form of 'difficult' is 'more difficult'."},
    {q:"She is the ___ student in the entire school.", choices:["smartest","smarter","most smart","more smart"], answer:0, expl:"Superlative of short adjectives: add -est. 'Smartest' is correct."},
    {q:"He runs ___ than anyone else on the team.", choices:["more fast","fastest","faster","most fast"], answer:2, expl:"Comparative of 'fast' is 'faster' (short adjective + -er)."},
    // --- Subject-verb agreement ---
    {q:"Neither the teacher nor the students ___ ready for the fire drill.", choices:["was","is","were","has"], answer:2, expl:"With 'neither...nor', the verb agrees with the nearest subject: 'students' (plural) \u2192 'were'."},
    {q:"Each of the students ___ required to bring a notebook.", choices:["are","were","is","have"], answer:2, expl:"'Each of' takes a singular verb: 'Each of the students is required...'"},
    {q:"The news ___ surprising to everyone.", choices:["were","are","was","have been"], answer:2, expl:"'News' is uncountable and takes a singular verb: 'The news was surprising.'"},
    {q:"She is used to ___ up early for school.", choices:["wake","waking","to wake","woke"], answer:1, expl:"'Used to' + gerund means accustomed to: 'used to waking up'."}
  ],
  reading: [
    {q:"\"Maria had been working on her history project for three days. Although she felt exhausted, she was determined to finish before the deadline. When she finally submitted it, she felt an overwhelming sense of relief.\" \u2014 What does 'overwhelming' most closely mean here?",
     choices:["Small and quiet","Very strong and intense","Disappointing and sad","Completely unexpected"], answer:1, expl:"Her relief after finishing was very strong and intense."},
    {q:"\"The group couldn't agree on a topic for their science presentation. After a long discussion, they finally chose renewable energy because everyone found it interesting.\" \u2014 Why did the group pick renewable energy?",
     choices:["The teacher told them to","It was the easiest topic","Everyone found it interesting","It was the only option left"], answer:2, expl:"The passage states 'because everyone found it interesting'."},
    {q:"\"James forgot to bring his permission slip for the field trip. His teacher said he could call his parents to get verbal permission instead.\" \u2014 What was James's problem?",
     choices:["He lost his bus pass","He forgot his permission slip","His parents were out of town","The field trip was cancelled"], answer:1, expl:"The first sentence says 'James forgot to bring his permission slip'."},
    {q:"\"Aisha noticed that her friend Priya had been quiet all week. During lunch, Aisha asked if everything was okay. Priya admitted she was stressed about her parents moving to a new city.\" \u2014 What can you infer about Aisha?",
     choices:["She is too busy to care about friends","She is observant and caring","She is also moving away","She doesn't like Priya"], answer:1, expl:"Aisha noticed Priya was quiet and asked about it \u2014 this shows she pays attention and cares."},
    {q:"\"After their argument, both Ravi and Sam avoided each other for days. Eventually, Ravi sent a message apologizing. Sam replied that he had also been meaning to say sorry.\" \u2014 What is the main idea of this passage?",
     choices:["Ravi and Sam are no longer friends","Arguments are always someone's fault","Both friends wanted to make up","Sam refused to forgive Ravi"], answer:2, expl:"Both Ravi and Sam apologized, showing they each wanted to reconcile."},
    {q:"\"The basketball team had lost five games in a row. Their coach decided to change the training schedule and focus more on defense. In the next game, they won by twelve points.\" \u2014 What change led to the team's improvement?",
     choices:["They got new players","They practiced less often","They focused more on defense","They changed their uniforms"], answer:2, expl:"The passage says the coach decided to 'focus more on defense' and then they won."},
    {q:"\"Despite being the shortest player on the team, Yuki was the fastest. Her speed allowed her to steal the ball more often than anyone else.\" \u2014 What is Yuki's main strength?",
     choices:["Her height","Her speed","Her shooting accuracy","Her defensive skills"], answer:1, expl:"'Yuki was the fastest' and her speed helped her steal the ball."},
    {q:"\"Photosynthesis is the process by which plants convert sunlight into energy. Without it, plants could not produce the food they need to grow. This process also releases oxygen into the air.\" \u2014 According to the passage, what does photosynthesis release?",
     choices:["Carbon dioxide","Water vapor","Oxygen","Nitrogen"], answer:2, expl:"'This process also releases oxygen into the air.'"},
    {q:"\"The water cycle begins when the sun heats water in oceans and lakes, causing it to evaporate. The water vapor rises, cools, and forms clouds. Eventually, it falls back to Earth as precipitation.\" \u2014 What causes water to evaporate?",
     choices:["Wind pushing the water","Heat from the sun","Cold temperatures","Gravity pulling the water"], answer:1, expl:"'The sun heats water...causing it to evaporate'."},
    {q:"\"On their class trip to Kyoto, the students visited several ancient temples. Their guide explained that some of the buildings were over 500 years old. Many students were amazed that the wooden structures had survived for so long.\" \u2014 What surprised the students?",
     choices:["How modern the temples looked","How expensive the tickets were","How long the wooden buildings had lasted","How crowded the city was"], answer:2, expl:"Students 'were amazed that the wooden structures had survived for so long'."},
    {q:"\"During the exchange program in London, Hana found it difficult to understand British English at first. After two weeks, she noticed that she could follow conversations much more easily.\" \u2014 What happened after two weeks?",
     choices:["Hana decided to go home early","Hana's listening improved","Hana stopped speaking English","Hana switched to a different school"], answer:1, expl:"She 'could follow conversations much more easily' \u2014 her listening got better."},
    {q:"\"The substitute teacher handed out a worksheet that no one had seen before. Several students raised their hands to ask questions, but the substitute wasn't sure of the answers either. Eventually, one student found the instructions in their textbook.\" \u2014 What can you infer about the substitute?",
     choices:["They were well prepared for the class","They were not familiar with the lesson plan","They refused to help the students","They had taught this class before"], answer:1, expl:"The substitute didn't know the answers \u2014 they were unfamiliar with the lesson."},
    {q:"\"Leo always completed his assignments on time, but this week he missed two deadlines. His best friend noticed and asked if something was wrong. Leo explained that his grandmother was in the hospital and he couldn't focus.\" \u2014 Why did Leo miss his deadlines?",
     choices:["He forgot about them","He was busy playing games","He was worried about his grandmother","He didn't understand the assignments"], answer:2, expl:"Leo said his grandmother was in the hospital and he couldn't focus."},
    {q:"\"The school announced that the annual science fair would now include a category for digital projects such as apps and websites. Many students who had never entered before said they were excited to participate this year.\" \u2014 Why were more students interested this year?",
     choices:["The prizes were bigger","A new digital category was added","The science fair was moved to a weekend","Teachers required everyone to enter"], answer:1, expl:"The new digital category attracted students who hadn't entered before."},
    {q:"\"Although the experiment did not produce the results they expected, the students learned an important lesson: negative results can be just as valuable as positive ones because they help eliminate wrong hypotheses.\" \u2014 What is the main message of this passage?",
     choices:["Failed experiments are a waste of time","Students should always get the expected result","Unexpected results can still teach you something","Only positive results matter in science"], answer:2, expl:"'Negative results can be just as valuable' \u2014 you learn from unexpected outcomes."},
    // --- New reading passages ---
    {q:"\"The ancient Egyptians built the pyramids as tombs for their pharaohs. The largest, the Great Pyramid of Giza, was constructed using over two million stone blocks. Historians believe it took about 20 years and tens of thousands of workers to complete.\" \u2014 What was the purpose of the pyramids?",
     choices:["To store food for the kingdom","To serve as tombs for pharaohs","To protect the city from invaders","To observe the stars"], answer:1, expl:"The first sentence states the pyramids were built 'as tombs for their pharaohs'."},
    {q:"\"In 1969, astronaut Neil Armstrong became the first person to walk on the moon. He famously said, 'That's one small step for man, one giant leap for mankind.' The event was watched on television by an estimated 600 million people worldwide.\" \u2014 Why was this event significant?",
     choices:["It was the first television broadcast","It was the cheapest space mission","It was the first time a human walked on the moon","It proved the moon was made of cheese"], answer:2, expl:"Armstrong was 'the first person to walk on the moon'."},
    {q:"\"Coral reefs are sometimes called the 'rainforests of the sea' because they support such a wide variety of life. Although they cover less than 1% of the ocean floor, they are home to about 25% of all marine species. Rising ocean temperatures, however, are causing coral bleaching, which threatens these ecosystems.\" \u2014 What is the main threat to coral reefs mentioned here?",
     choices:["Overfishing by commercial boats","Pollution from nearby cities","Rising ocean temperatures","Underwater earthquakes"], answer:2, expl:"'Rising ocean temperatures...are causing coral bleaching'."},
    {q:"\"The school cafeteria started offering a salad bar last month. At first, only a few students tried it. But after the school posted nutrition facts and recipes on social media, the salad bar became one of the most popular lunch options.\" \u2014 What made the salad bar popular?",
     choices:["The school made it mandatory","Students were given free samples","Nutrition facts and recipes were shared on social media","The price was reduced to zero"], answer:2, expl:"Popularity grew 'after the school posted nutrition facts and recipes on social media'."},
    {q:"\"Thomas Edison is often credited with inventing the light bulb, but he actually improved upon earlier designs by other inventors. His version lasted over 1,200 hours, making it the first practical light bulb for everyday use.\" \u2014 What did Edison actually do?",
     choices:["He was the first to discover electricity","He improved the light bulb to make it practical","He invented the light bulb from scratch","He sold other inventors' work as his own"], answer:1, expl:"He 'improved upon earlier designs' to create 'the first practical light bulb'."},
    {q:"\"A recent study found that students who eat breakfast perform better on tests than those who skip it. Researchers believe that breakfast provides the brain with glucose, which is essential for concentration and memory.\" \u2014 According to the passage, why does breakfast help with tests?",
     choices:["It makes students arrive on time","It provides glucose for the brain","It reduces stress before exams","It helps students sleep better"], answer:1, expl:"'Breakfast provides the brain with glucose, which is essential for concentration and memory'."},
    {q:"\"The Amazon rainforest produces about 20% of the world's oxygen. It is also home to millions of species of plants and animals, many of which have not yet been discovered. Deforestation, however, is shrinking the forest at an alarming rate.\" \u2014 What does the passage imply about the Amazon?",
     choices:["All species there have been documented","It is not important for the planet","It is both valuable and threatened","Deforestation has already stopped"], answer:2, expl:"The passage highlights the Amazon's value (oxygen, species) and its threat (deforestation)."},
    {q:"\"During the Industrial Revolution, many people moved from farms to cities to work in factories. Working conditions were often dangerous, and children as young as five were employed for long hours. Over time, laws were passed to protect workers and ban child labor.\" \u2014 What problem did new laws address?",
     choices:["Farmers not growing enough food","Dangerous conditions and child labor in factories","Too many people living on farms","Factories producing too many goods"], answer:1, expl:"The passage describes dangerous conditions and child labor, then says laws were passed to address them."},
    {q:"\"Renewable energy sources like solar and wind power are becoming cheaper every year. In some countries, solar energy is now less expensive than coal. Experts predict that by 2050, most of the world's electricity will come from renewable sources.\" \u2014 What trend does the passage describe?",
     choices:["Coal is becoming more popular","Renewable energy is getting cheaper and growing","Wind power is being banned","Solar panels are too expensive to use"], answer:1, expl:"Renewable energy is 'becoming cheaper every year' and will grow to produce most electricity."},
    {q:"\"In Japan, there is a practice called 'forest bathing' or shinrin-yoku, which involves spending quiet time in nature. Studies have shown that it can lower blood pressure, reduce stress, and improve mood. Doctors in some countries now prescribe nature walks as a form of treatment.\" \u2014 What is the main benefit of forest bathing?",
     choices:["It teaches people about trees","It improves physical and mental health","It is a competitive sport","It helps people learn Japanese"], answer:1, expl:"The passage lists health benefits: 'lower blood pressure, reduce stress, and improve mood'."},
    {q:"\"The Great Wall of China stretches over 13,000 miles across northern China. It was built over many centuries by different dynasties to protect against invasions from the north. Today, it is one of the most visited tourist attractions in the world.\" \u2014 Why was the Great Wall originally built?",
     choices:["As a tourist attraction","To separate different cities","To protect against invasions","To create a trade route"], answer:2, expl:"It was built 'to protect against invasions from the north'."},
    {q:"\"Scientists have discovered that octopuses have three hearts and blue blood. Two of the hearts pump blood to the gills, while the third pumps it to the rest of the body. Their blood is blue because it contains copper instead of iron.\" \u2014 Why is octopus blood blue?",
     choices:["Because they live in deep water","Because their blood contains copper instead of iron","Because they eat blue fish","Because they have three hearts"], answer:1, expl:"'Their blood is blue because it contains copper instead of iron.'"},
    {q:"\"A group of students started a composting program at their school. They collected food waste from the cafeteria and turned it into fertilizer for the school garden. Within a year, the school had reduced its waste by 30% and grown over 50 kilograms of vegetables.\" \u2014 What was the result of the composting program?",
     choices:["The cafeteria closed down","The school reduced waste and grew vegetables","Students stopped eating lunch","The garden was removed"], answer:1, expl:"The school 'reduced its waste by 30% and grown over 50 kilograms of vegetables'."},
    {q:"\"Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that was still edible. This is because honey has very low moisture and high acidity, which prevent bacteria from growing.\" \u2014 Why doesn't honey spoil?",
     choices:["It is kept in sealed tombs","It contains special chemicals added by bees","It has low moisture and high acidity","It is always stored in cold temperatures"], answer:2, expl:"'Honey has very low moisture and high acidity, which prevent bacteria from growing.'"},
    {q:"\"Many schools around the world have started teaching coding as a regular subject. Supporters say it develops logical thinking and problem-solving skills. Critics argue that not all students need to learn programming and that other subjects deserve more time.\" \u2014 What is the critics' concern?",
     choices:["Coding is too easy for students","Computers are too expensive for schools","Other subjects may lose time to coding","All students already know how to code"], answer:2, expl:"Critics argue 'other subjects deserve more time' \u2014 coding may take time away from them."}
  ],
  listening: [
    // Type 1: What did you hear?
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"She submitted her assignment early.",
     choices:["She submitted her assignment early","She submitted her assignment lately","She submitted her essay early","He submitted his assignment early"], answer:0, expl:"Listen for: 'She', 'assignment', and 'early'."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"The experiment was conducted by the students.",
     choices:["The experiment was conducted by the teachers","The experiment was connected by the students","The experiment was conducted by the students","The experience was conducted by the students"], answer:2, expl:"'Conducted' (not 'connected') and 'students' (not 'teachers') are key."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"Please bring your textbook to class tomorrow.",
     choices:["Please bring your notebook to class tomorrow","Please bring your textbook to class today","Please bring your textbook to class tomorrow","Please take your textbook to class tomorrow"], answer:2, expl:"'Textbook' (not notebook), 'bring' (not take), 'tomorrow' (not today)."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"He felt relieved after finishing the test.",
     choices:["He felt relaxed after finishing the test","He felt relieved after finishing the task","He felt relieved after finishing the test","He felt believed after finishing the test"], answer:2, expl:"'Relieved' (not relaxed/believed) and 'test' (not task)."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"The library is closed on weekends.",
     choices:["The library is closed on weekdays","The library is open on weekends","The library is closed on weekends","The laboratory is closed on weekends"], answer:2, expl:"'Library' (not laboratory), 'closed' (not open), 'weekends' (not weekdays)."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"The students were required to submit their essays by Wednesday.",
     choices:["The students were required to submit their essays by Wednesday","The students were required to submit their exams by Wednesday","The students were requested to submit their essays by Thursday","The students were required to submit their essays by Monday"], answer:0, expl:"'Required' (not requested), 'essays' (not exams), 'Wednesday' (not Thursday/Monday)."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"The principal announced a new recycling program for the school.",
     choices:["The principal announced a new reading program for the school","The teacher announced a new recycling program for the school","The principal announced a new recycling program for the school","The principal cancelled the recycling program at the school"], answer:2, expl:"'Principal' (not teacher), 'announced' (not cancelled), 'recycling' (not reading)."},
    {q:"\uD83D\uDD0A Listen and choose what you heard.", speech:"Global warming is caused by an increase in greenhouse gases.",
     choices:["Global warming is caused by a decrease in greenhouse gases","Global warming is caused by an increase in greenhouse gases","Global warning is caused by an increase in greenhouse gases","Global warming is caused by an increase in green house plants"], answer:1, expl:"'Warming' (not warning), 'increase' (not decrease), 'gases' (not plants)."},
    // Type 2: What does it mean?
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"I'm running late for class.",
     choices:["I am exercising before class","I am going to be late for class","I am running to the classroom","I left class early"], answer:1, expl:"'Running late' is an idiom meaning 'going to be late'."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"Could you give me a hand with this project?",
     choices:["Could you lend me your hands","Could you help me with this project","Could you hand me the project","Could you clap for my project"], answer:1, expl:"'Give me a hand' is an idiom meaning 'help me'."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"The teacher told us to hand in our homework.",
     choices:["The teacher said to raise our hands","The teacher said to submit our homework","The teacher said to hold our homework","The teacher said to copy our homework"], answer:1, expl:"'Hand in' is a phrasal verb meaning 'submit' or 'turn in'."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"She has a lot on her plate this week.",
     choices:["She is eating a large meal","She is carrying many plates","She is very busy this week","She is cooking for many people"], answer:2, expl:"'A lot on her plate' means she has many tasks and responsibilities."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"Let's call it a day.",
     choices:["Let's make a phone call today","Let's name this day","Let's stop working for today","Let's start a new day"], answer:2, expl:"'Call it a day' means to stop working and finish for today."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"He hit the books before the exam.",
     choices:["He threw his books","He studied hard","He punched his textbook","He bought new books"], answer:1, expl:"'Hit the books' is an idiom meaning to study hard."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"The test was a piece of cake.",
     choices:["The test included cake","The test was about baking","The test was very easy","The test was very long"], answer:2, expl:"'A piece of cake' means something very easy to do."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"She is on the same page as the rest of the team.",
     choices:["She is reading the same book","She agrees with the team","She is sitting next to them","She is writing on a page"], answer:1, expl:"'On the same page' means to agree or share the same understanding."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"Don't put all your eggs in one basket.",
     choices:["Don't carry too many eggs","Don't buy too many baskets","Don't risk everything on one option","Don't eat too many eggs"], answer:2, expl:"This idiom means don't risk everything on a single plan."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"The project is back to square one.",
     choices:["The project moved to room one","The project is at the starting point again","The project is almost finished","The project is shaped like a square"], answer:1, expl:"'Back to square one' means starting over from the very beginning."},
    // Type 3: Complete the sentence
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'The students were ___ about the field trip.'", speech:"The students were excited about the field trip.",
     choices:["exhausted","anxious","excited","embarrassed"], answer:2, expl:"The audio says 'excited'."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'You ___ finish your homework before watching TV.'", speech:"You should finish your homework before watching TV.",
     choices:["might","would","could","should"], answer:3, expl:"The audio says 'should'."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'The science fair ___ held in the gymnasium last Friday.'", speech:"The science fair was held in the gymnasium last Friday.",
     choices:["is","was","has","will be"], answer:1, expl:"The audio says 'was'. Past tense passive voice."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'She ___ been studying English for three years.'", speech:"She has been studying English for three years.",
     choices:["have","has","had","is"], answer:1, expl:"The audio says 'has'. Present perfect continuous."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'If it ___ tomorrow, the game will be cancelled.'", speech:"If it rains tomorrow, the game will be cancelled.",
     choices:["rained","raining","rains","rain"], answer:2, expl:"The audio says 'rains'. First conditional: If + present simple."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'The teacher ___ us to open our textbooks.'", speech:"The teacher asked us to open our textbooks.",
     choices:["told","asked","forced","let"], answer:1, expl:"The audio says 'asked'."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'We need to ___ the results of the experiment.'", speech:"We need to analyze the results of the experiment.",
     choices:["memorize","analyze","ignore","repeat"], answer:1, expl:"The audio says 'analyze'. Analyze means to examine in detail."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'The project is ___ on Friday.'", speech:"The project is due on Friday.",
     choices:["done","due","new","free"], answer:1, expl:"The audio says 'due'. 'Due on Friday' means the deadline is Friday."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'She ___ working on her essay for two hours.'", speech:"She has been working on her essay for two hours.",
     choices:["has been","had been","was","is"], answer:0, expl:"The audio says 'has been'. Present perfect continuous for an ongoing action."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'The museum ___ visited by thousands of tourists every year.'", speech:"The museum is visited by thousands of tourists every year.",
     choices:["is","was","has","will"], answer:0, expl:"The audio says 'is'. Present passive for a regular occurrence."},
    {q:"\uD83D\uDD0A Listen and choose the meaning.", speech:"We should get the ball rolling on this project.",
     choices:["We should play ball during the project","We should start the project","We should roll a ball across the room","We should finish the project quickly"], answer:1, expl:"'Get the ball rolling' means to start or begin something."},
    {q:"\uD83D\uDD0A Listen and choose the missing word: 'The students ___ to work in groups for the assignment.'", speech:"The students were asked to work in groups for the assignment.",
     choices:["were asked","have asked","are asking","will ask"], answer:0, expl:"The audio says 'were asked'. Past passive: the students received the instruction."}
  ]
};

// ===== ENEMY DATA (rebalanced: 4-6 hits to defeat) =====
const enemies = [
  {name:"Slime",   emoji:"\uD83D\uDFE2", hp:10, atk:2,  def:0, gold:5,  minLv:1},
  {name:"Goblin",  emoji:"\uD83D\uDC7A", hp:16, atk:4,  def:1, gold:10, minLv:1},
  {name:"Bat",     emoji:"\uD83E\uDD87", hp:14, atk:3,  def:1, gold:8,  minLv:3},
  {name:"Orc",     emoji:"\uD83D\uDC79", hp:24, atk:7,  def:2, gold:18, minLv:6},
  {name:"Wolf",    emoji:"\uD83D\uDC3A", hp:20, atk:6,  def:2, gold:15, minLv:6},
  {name:"Wizard",  emoji:"\uD83E\uDDD9", hp:20, atk:9,  def:2, gold:22, minLv:11},
  {name:"Golem",   emoji:"\uD83D\uDDFF", hp:30, atk:5,  def:5, gold:25, minLv:11},
  {name:"Dragon",  emoji:"\uD83D\uDC09", hp:40, atk:14, def:4, gold:40, minLv:21}
];

// ===== SHOP ITEMS =====
const shopItems = [
  {id:"iron_sword",     name:"Iron Sword",     icon:"\u2694\uFE0F", effect:"ATK +3",  stat:"atk", value:3,  cost:50,  type:"equip"},
  {id:"steel_sword",    name:"Steel Sword",    icon:"\uD83D\uDDE1\uFE0F", effect:"ATK +6",  stat:"atk", value:6,  cost:120, type:"equip"},
  {id:"dragon_blade",   name:"Dragon Blade",   icon:"\uD83D\uDD25", effect:"ATK +12", stat:"atk", value:12, cost:300, type:"equip"},
  {id:"leather_shield", name:"Leather Shield", icon:"\uD83D\uDEE1\uFE0F", effect:"DEF +3",  stat:"def", value:3,  cost:50,  type:"equip"},
  {id:"iron_shield",    name:"Iron Shield",    icon:"\uD83D\uDEE1\uFE0F", effect:"DEF +6",  stat:"def", value:6,  cost:120, type:"equip"},
  {id:"dragon_armor",   name:"Dragon Armor",   icon:"\uD83D\uDC89", effect:"DEF +12", stat:"def", value:12, cost:300, type:"equip"},
  {id:"hp_potion",      name:"HP Potion",      icon:"\uD83E\uDDEA", effect:"Restore 20 HP in battle", stat:"hp", value:20, cost:30, type:"consumable"}
];

// ===== STORY CHAPTERS =====
const storyChapters = [
  {id:0, title:"Chapter 1: The Enchanted Forest", reqLevel:5, icon:"\uD83C\uDF32", badge:"Forest Hero", goldReward:80, bonusHp:4,
    intro:"Deep in the Enchanted Forest, strange magic has been twisting the trees and scaring the animals. A mysterious Forest Witch has taken control, casting dark spells from her hidden lair. Your monster must brave the enchanted paths and defeat her to restore peace.",
    mobs:[{name:"Wild Mushroom",emoji:"\uD83C\uDF44",hp:20,atk:5,def:2,gold:8},{name:"Shadow Fox",emoji:"\uD83E\uDD8A",hp:25,atk:6,def:2,gold:10}],
    boss:{name:"Forest Witch",emoji:"\uD83E\uDDD9\u200D\u2640\uFE0F",hp:60,atk:10,def:4,gold:40}},
  {id:1, title:"Chapter 2: The Crystal Caves", reqLevel:10, icon:"\uD83D\uDC8E", badge:"Crystal Champion", goldReward:120, bonusHp:6,
    intro:"Beneath the mountains lie the Crystal Caves, where precious gems glow in the darkness. But a massive Stone Golem guards the deepest cavern, crushing anyone who dares to enter. Only the bravest adventurers can shatter its stone armor.",
    mobs:[{name:"Cave Bat",emoji:"\uD83E\uDD87",hp:30,atk:8,def:3,gold:12},{name:"Rock Crab",emoji:"\uD83E\uDD80",hp:35,atk:7,def:6,gold:14},{name:"Crystal Spider",emoji:"\uD83D\uDD77\uFE0F",hp:28,atk:10,def:3,gold:13}],
    boss:{name:"Stone Golem",emoji:"\uD83D\uDDFF",hp:100,atk:14,def:8,gold:60}},
  {id:2, title:"Chapter 3: The Sky Kingdom", reqLevel:15, icon:"\u2601\uFE0F", badge:"Sky Guardian", goldReward:160, bonusHp:8,
    intro:"High above the clouds floats the Sky Kingdom, a once-peaceful realm now terrorized by the Storm Griffin. Lightning strikes without warning, and fierce winds blow through the golden halls. You must fly higher than ever before to challenge this beast.",
    mobs:[{name:"Wind Sprite",emoji:"\uD83C\uDF2C\uFE0F",hp:35,atk:11,def:4,gold:16},{name:"Thunder Hawk",emoji:"\uD83E\uDD85",hp:40,atk:13,def:4,gold:18}],
    boss:{name:"Storm Griffin",emoji:"\u26A1",hp:140,atk:18,def:6,gold:80}},
  {id:3, title:"Chapter 4: The Shadow Realm", reqLevel:20, icon:"\uD83C\uDF11", badge:"Shadow Breaker", goldReward:200, bonusHp:10,
    intro:"The Shadow Realm exists between dimensions, a twisted mirror of the real world. The Dark Sorcerer rules here, feeding on fear and doubt. His dark magic is powerful, but your knowledge of English is an even stronger weapon. Face your deepest fears and bring light to the darkness.",
    mobs:[{name:"Phantom",emoji:"\uD83D\uDC7B",hp:45,atk:15,def:5,gold:20},{name:"Dark Knight",emoji:"\u2694\uFE0F",hp:55,atk:16,def:8,gold:24},{name:"Nightmare",emoji:"\uD83D\uDE08",hp:50,atk:18,def:5,gold:22}],
    boss:{name:"Dark Sorcerer",emoji:"\uD83E\uDDD9",hp:180,atk:22,def:8,gold:100}},
  {id:4, title:"Chapter 5: The Dragon's Throne", reqLevel:30, icon:"\uD83D\uDC09", badge:"Dragon Slayer", goldReward:300, bonusHp:15,
    intro:"At the peak of the world stands the Dragon's Throne, where the Ancient Dragon has slept for a thousand years. Now it has awakened, and its fiery breath threatens to engulf the entire land. Only a true master of language and courage can challenge the most powerful creature in existence.",
    mobs:[{name:"Lava Serpent",emoji:"\uD83D\uDC0D",hp:60,atk:20,def:7,gold:28},{name:"Fire Elemental",emoji:"\uD83D\uDD25",hp:55,atk:22,def:6,gold:30},{name:"Dragon Guard",emoji:"\uD83D\uDC32",hp:70,atk:19,def:10,gold:32}],
    boss:{name:"Ancient Dragon",emoji:"\uD83D\uDC09",hp:250,atk:28,def:10,gold:150}}
];

// Boss-tier questions (harder)
const bossQuestions = {
  vocabulary: [
    {q:"The author's ___ description of the sunset made readers feel like they were there.", choices:["dull","vivid","reluctant","ambiguous"], answer:1, expl:"Vivid means producing strong, clear images in the mind."},
    {q:"Breaking the school rules has serious ___.", choices:["consequences","phenomena","hypotheses","absences"], answer:0, expl:"Consequences are the results or effects of an action, especially negative ones."},
    {q:"A \"phenomenon\" is ___.", choices:["a common everyday event","a type of experiment","an observable event that is remarkable","a prediction about the future"], answer:2, expl:"A phenomenon is something observable and remarkable."},
    {q:"He was ___ to join the debate team because he feared public speaking.", choices:["ambitious","confident","reluctant","grateful"], answer:2, expl:"Reluctant means unwilling or hesitant to do something."},
    {q:"The instructions were ___, so nobody knew what to do.", choices:["vivid","precise","reluctant","ambiguous"], answer:3, expl:"Ambiguous means unclear, having more than one possible meaning."},
    {q:"She gave a ___ argument that convinced the entire class.", choices:["fragile","compelling","reluctant","trivial"], answer:1, expl:"Compelling means very convincing and powerful."},
    {q:"The scientist needed more ___ before drawing a conclusion.", choices:["evidence","absence","permission","curriculum"], answer:0, expl:"Evidence is facts or information that support or prove something."},
    {q:"His excuse sounded ___, so the teacher didn't believe him.", choices:["credible","inevitable","implausible","preliminary"], answer:2, expl:"Implausible means not believable or hard to accept as true."}
  ],
  grammar: [
    {q:"If I ___ known about the test, I would have studied harder.", choices:["have","has","had","would"], answer:2, expl:"Third conditional: If + had + past participle."},
    {q:"She wishes she ___ more time to finish the project.", choices:["has","have","had","having"], answer:2, expl:"'Wish' + past simple for unreal desires. 'Had' is subjunctive."},
    {q:"Not only ___ she pass the exam, but she also got the highest score.", choices:["does","did","has","was"], answer:1, expl:"'Not only' at the start requires inversion. Past tense \u2192 'did she pass'."},
    {q:"The research paper, ___ was published last month, received international attention.", choices:["that","who","which","whom"], answer:2, expl:"Non-restrictive clause (with commas) uses 'which', not 'that'."},
    {q:"Had the students ___ more carefully, they would have found the error.", choices:["read","reads","reading","been read"], answer:0, expl:"Inverted third conditional: Had + subject + past participle."},
    {q:"It is essential that every student ___ the assignment on time.", choices:["submits","submit","submitted","submitting"], answer:1, expl:"Subjunctive after 'essential that': use the base form 'submit'."},
    {q:"The teacher insisted that he ___ his essay before the deadline.", choices:["rewrites","rewrite","rewrote","rewriting"], answer:1, expl:"Subjunctive after 'insisted that': use the base form 'rewrite'."},
    {q:"Neither the students nor the teacher ___ aware of the schedule change.", choices:["were","was","are","have been"], answer:1, expl:"With 'neither...nor', verb agrees with nearest subject: 'teacher' (singular) \u2192 'was'."}
  ],
  reading: [
    {q:"\"The expedition team had been climbing for six days when the weather suddenly changed. Dark clouds gathered, and the temperature dropped by 15 degrees in an hour. The team leader decided to set up camp immediately rather than risk the summit.\" \u2014 The leader's decision shows he valued ___.",
     choices:["reaching the top quickly","the team's safety over the goal","proving his courage","ignoring the weather forecast"], answer:1, expl:"He prioritized safety over reaching the summit."},
    {q:"\"Dr. Chen's research revealed that students who read for pleasure scored significantly higher on vocabulary tests than those who only read textbooks. She suggested that schools should encourage free reading time during the school day.\" \u2014 What is Dr. Chen's main recommendation?",
     choices:["Stop using textbooks entirely","Test vocabulary more often","Add free reading time to school","Only read fiction books"], answer:2, expl:"She 'suggested that schools should encourage free reading time'."},
    {q:"\"The ancient Romans built aqueducts to carry water from distant sources into their cities. Some of these structures still stand today, over two thousand years later, demonstrating the remarkable engineering skills of that era.\" \u2014 The word 'remarkable' most closely means ___.",
     choices:["ordinary and common","impressive and noteworthy","outdated and useless","simple and basic"], answer:1, expl:"Structures lasting 2000+ years are impressive and noteworthy."},
    {q:"\"When Maya moved to a new country, she couldn't understand anyone at school. But she noticed that smiling was a universal language. Within a month, she had made several friends, even before she could speak their language fluently.\" \u2014 What helped Maya make friends?",
     choices:["Learning the language quickly","Her excellent grades","Her friendly attitude and smiles","Her teacher introducing her"], answer:2, expl:"'Smiling was a universal language' and she made friends before speaking fluently."}
  ]
};

// ===== MONSTER ROSTER & GACHA =====
const monsterRoster = [
  {id:1,name:'Blue Slime',element:'Water',emoji:'\uD83C\uDF0A',color:'#2980b9',rarity:'Normal',hp:20,atk:5,def:3,trait:'Starter',img:'monster-1.png',specialty:{cats:['vocabulary'],bonus:0.10},
    maxStages:4,evoThresholds:[100,200,350],evoBonus:{hp:5,atk:2,def:2,spd:2},stageNames:['Baby Slime','Brave Slime','Slime Prince','Slime King']},
  {id:2,name:'Fire Fox',element:'Fire',emoji:'\uD83D\uDD25',color:'#e74c3c',rarity:'Normal',hp:18,atk:8,def:2,trait:'ATK +20%',img:'monster-2.png',specialty:{cats:['grammar'],bonus:0.10},
    maxStages:2,evoThresholds:[60],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Fire Fox','Inferno Fox']},
  {id:3,name:'Stone Golem',element:'Earth',emoji:'\uD83C\uDF0D',color:'#8B6914',rarity:'Normal',hp:25,atk:4,def:10,trait:'DEF +30%',img:'monster-3.png',specialty:{cats:['reading'],bonus:0.10},
    maxStages:2,evoThresholds:[60],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Stone Golem','Iron Golem']},
  {id:4,name:'Thunder Bird',element:'Thunder',emoji:'\u26A1',color:'#f1c40f',rarity:'Rare',hp:18,atk:7,def:4,trait:'SPD +30%',img:'monster-4.png',specialty:{cats:['listening'],bonus:0.10},
    maxStages:3,evoThresholds:[40,80],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Thunder Bird','Storm Raptor','Lightning Emperor']},
  {id:5,name:'Ice Wolf',element:'Ice',emoji:'\u2744\uFE0F',color:'#5dade2',rarity:'Rare',hp:28,atk:6,def:5,trait:'HP +30%',img:'monster-5.png',specialty:{cats:['vocabulary'],bonus:0.15},
    maxStages:3,evoThresholds:[40,80],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Ice Wolf','Frost Fenrir','Blizzard Alpha']},
  {id:6,name:'Dark Bat',element:'Dark',emoji:'\uD83C\uDF11',color:'#6c3483',rarity:'Rare',hp:22,atk:9,def:5,trait:'Balanced',img:'monster-6.png',specialty:{cats:['grammar'],bonus:0.15},
    maxStages:3,evoThresholds:[40,80],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Dark Bat','Shadow Wyvern','Void Dracula']},
  {id:7,name:'Wind Dragon',element:'Wind',emoji:'\uD83D\uDCA8',color:'#27ae60',rarity:'Super Rare',hp:25,atk:11,def:7,trait:'All +15%',img:'monster-7.png',specialty:{cats:['reading'],bonus:0.15},
    maxStages:3,evoThresholds:[40,80],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Wind Dragon','Gale Serpent','Tempest God']},
  {id:8,name:'Lava Titan',element:'Fire/Earth',emoji:'\uD83C\uDF0B',color:'#d35400',rarity:'Super Rare',hp:22,atk:14,def:12,trait:'ATK+DEF',img:'monster-8.png',specialty:{cats:['listening'],bonus:0.15},
    maxStages:3,evoThresholds:[40,80],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Lava Titan','Magma Colossus','Volcano King']},
  {id:9,name:'Storm Phoenix',element:'Thunder/Wind',emoji:'\uD83E\uDD85',color:'#8e44ad',rarity:'Super Rare',hp:28,atk:12,def:8,trait:'Epic evo',img:'monster-9.png',specialty:{cats:['grammar','listening'],bonus:0.20},
    maxStages:3,evoThresholds:[40,80],evoBonus:{hp:5,atk:3,def:2,spd:1},stageNames:['Storm Phoenix','Thunder Quetzal','Eternal Phoenix']},
  {id:10,name:'Celestial Beast',element:'Light',emoji:'\u2728',color:'#f1c40f',rarity:'Legend',hp:35,atk:15,def:12,trait:'All highest',img:'monster-10.png',specialty:{cats:['vocabulary','grammar','reading','listening'],bonus:0.15},
    maxStages:2,evoThresholds:[60],evoBonus:{hp:10,atk:5,def:4,spd:2},stageNames:['Celestial Beast','Divine Celestial']}
];
